/**
 * Permission definitions for Role & Permissions (admin editing user-level permissions).
 * Each company (office config) has its own role defaults; users can have custom overrides.
 * Categories and keys match the Whitebox UI: Attendance, Request, Reporting, Admin.
 */

export const PERMISSION_CATEGORIES = {
  ATTENDANCE_MANAGEMENT: "attendance_management",
  REQUEST_MANAGEMENT: "request_management",
  REPORTING_ANALYTICS: "reporting_analytics",
  ADMIN_RELATED: "admin_related",
  COMMUNITY_POSTS: "community_posts",
};

/** All permission keys with category, label, and description for UI and validation */
export const PERMISSION_DEFINITIONS = [
  // --- Attendance Management ---
  {
    key: "view_attendance_status",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "View attendance status",
    description: "Allow users to view their own attendance status",
  },
  {
    key: "check_in",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Check in",
    description: "Allow users to check in at office",
  },
  {
    key: "request_work_from_home",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Request work from home",
    description: "Allow user to request work from home",
  },
  {
    key: "view_all_attendance",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "View all attendance",
    description: "Allow users to view all company attendance",
  },
  {
    key: "can_edit_own_attendance",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Can edit own attendance",
    description: "Allow users to edit their own attendance",
  },
  {
    key: "signature_attendance_manage",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Signature attendance manage",
    description: "Allow user to manage signature attendance",
  },
  {
    key: "can_edit_all_attendance",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Can edit all attendance",
    description: "Allow users to edit all attendance",
  },
  {
    key: "can_edit_team_attendance",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Can edit team attendance",
    description: "Allow team lead/manager to edit attendance of their team members only",
  },
  {
    key: "qr_code_attendance_manage",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "QR code attendance manage",
    description: "Allow user to manage QR Code attendance",
  },
  {
    key: "can_view_all_company_leaves",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Can view all company leaves",
    description: "Allow users to view all company leaves",
  },
  {
    key: "view_all_leaves_status",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "View all leaves status",
    description: "Allow users to view their leaves status",
  },
  {
    key: "can_check_out",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Can check-out",
    description: "Allow users to check-out from office",
  },
  {
    key: "save_all_attendance",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Save all attendance",
    description: "Save all attendance",
  },
  {
    key: "check_out",
    category: PERMISSION_CATEGORIES.ATTENDANCE_MANAGEMENT,
    label: "Check out",
    description: "Allow users to check out",
  },
  // --- Request Management ---
  {
    key: "can_make_new_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Can make new requests",
    description: "Allow users to make new requests",
  },
  {
    key: "approve_wfh",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Approve WFH",
    description: "Approve work from home requests",
  },
  {
    key: "cancel_leave_update_leave_request",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Cancel leave/Update leave request",
    description: "Allow users to cancel or update leave requests",
  },
  {
    key: "apply_for_wfh",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Apply for WFH",
    description: "Allow user to apply for work from home",
  },
  {
    key: "can_approve_leave_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Can approve leave requests",
    description: "Allow users to approve leave requests",
  },
  {
    key: "configure_leave_request_type",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Configure leave request type",
    description: "Allow user to configure leave request type",
  },
  {
    key: "can_view_own_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Can view own requests",
    description: "Allow users to view their own requests",
  },
  {
    key: "view_other_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View other requests",
    description: "Allow users to view other requests",
  },
  {
    key: "can_view_all_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Can view all requests",
    description: "Allow users to view all requests",
  },
  {
    key: "manage_leave_rules",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Manage leave rules",
    description: "Allow user to manage leave rules",
  },
  {
    key: "view_leave_balance",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View leave balance",
    description: "Allow users to view their leave balance",
  },
  {
    key: "apply_for_leave",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Apply for leave",
    description: "Allow users to apply for leave",
  },
  {
    key: "view_leave_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View leave requests",
    description: "Allow users to view their own leave requests and pending count",
  },
  {
    key: "view_wfh_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View WFH requests",
    description: "Allow users to view their own work-from-home requests, approved list, and pending count",
  },
  {
    key: "request_working_hours",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Request working hours",
    description: "Allow users to submit working hours change requests",
  },
  {
    key: "view_working_hours_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View working hours requests",
    description: "Allow users to view their own working hours requests, delete, edit own, and pending count",
  },
  {
    key: "approve_working_hours_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Approve working hours requests",
    description: "Allow users to approve or reject working hours requests",
  },
  // --- Reporting & Analytics ---
  {
    key: "view_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View reports",
    description: "Allow users to view reports",
  },
  {
    key: "export_payroll_data",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Export payroll data",
    description: "Export payroll data",
  },
  {
    key: "export_attendance_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Export attendance reports",
    description: "Export attendance reports",
  },
  {
    key: "export_all_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Export all reports",
    description: "Export all reports",
  },
  {
    key: "view_all_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View all reports",
    description: "Allow users to view all reports",
  },
  {
    key: "view_attendance_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View attendance reports",
    description: "Allow users to view attendance reports",
  },
  {
    key: "export_time_log_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Export time log reports",
    description: "Export time log reports",
  },
  {
    key: "view_time_log_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View time log reports",
    description: "Allow users to view time log reports",
  },
  {
    key: "view_audit_trail",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View audit trail",
    description: "Allow users to view audit trail",
  },
  {
    key: "manage_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Manage reports",
    description: "Allow users to manage reports",
  },
  {
    key: "view_reports_analytics",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View reports analytics",
    description: "Allow users to view reports analytics",
  },
  {
    key: "manage_all_reports",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Manage all reports",
    description: "Allow users to manage all reports",
  },
  {
    key: "config_report_settings",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Config report settings",
    description: "Allow user to config report settings",
  },
  // --- Admin Related ---
  {
    key: "manage_user_permissions",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage user permissions",
    description: "Manage user permissions",
  },
  {
    key: "manage_agents",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage agents",
    description: "Manage agents and staff",
  },
  {
    key: "manage_office_config",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage office config",
    description: "Manage office config",
  },
  {
    key: "configure_staff_schedules",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Configure staff schedules",
    description: "Configure staff schedules",
  },
  {
    key: "manage_teams",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage teams",
    description: "Manage teams",
  },
  {
    key: "manage_organization_settings",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage organization settings",
    description: "Manage organization settings",
  },
  {
    key: "manage_roles",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage roles",
    description: "Manage roles",
  },
  {
    key: "dynamic_settings",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Dynamic settings",
    description: "Dynamic settings",
  },
  // --- Request Management: specific keys (unique per action) ---
  {
    key: "view_recent_requests",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View recent requests",
    description: "Allow users to view recent requests (admin, team lead, manager)",
  },
  {
    key: "view_request_dashboard",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View request dashboard",
    description: "Allow users to view request dashboard counts (admin, team lead, manager)",
  },
  {
    key: "can_book_meeting_room",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "Book meeting room",
    description: "Allow users to book a meeting room",
  },
  {
    key: "view_meeting_room_bookings",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View meeting room bookings",
    description: "Allow users to view and manage their meeting room bookings",
  },
  // --- Bug (unique keys) ---
  {
    key: "report_bug",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Report bug",
    description: "Allow users to report a bug",
  },
  {
    key: "view_bugs",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View bugs",
    description: "Allow users to view bug reports",
  },
  {
    key: "manage_bugs",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Manage bugs",
    description: "Allow users to update status and delete bugs",
  },
  // --- Ticket (unique keys) ---
  {
    key: "create_ticket",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Create ticket",
    description: "Allow users to create a support ticket",
  },
  {
    key: "view_tickets",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View tickets",
    description: "Allow users to view tickets",
  },
  {
    key: "view_ticket_status_count",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "View ticket status count",
    description: "Allow users to view ticket status counts",
  },
  {
    key: "assign_ticket",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Assign ticket",
    description: "Allow users to assign tickets",
  },
  {
    key: "update_ticket_status",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Update ticket status",
    description: "Allow users to update ticket status",
  },
  {
    key: "edit_ticket",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Edit ticket",
    description: "Allow users to edit tickets",
  },
  {
    key: "delete_ticket",
    category: PERMISSION_CATEGORIES.REPORTING_ANALYTICS,
    label: "Delete ticket",
    description: "Allow users to delete tickets",
  },
  // --- Departments (admin vs manager scope) ---
  {
    key: "view_departments",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "View departments",
    description: "Allow users to view department list and details",
  },
  {
    key: "manage_departments",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage all departments",
    description: "Allow users to create, update, delete any department (admin)",
  },
  {
    key: "manage_own_department",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Manage own department",
    description: "Allow manager to manage their own department",
  },
  // --- Notifications (unique keys) ---
  {
    key: "view_notifications",
    category: PERMISSION_CATEGORIES.REQUEST_MANAGEMENT,
    label: "View notifications",
    description: "Allow users to view and read their notifications (common for all)",
  },
  {
    key: "send_test_notification",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "Send test notification",
    description: "Allow users to send test notification to all users (admin)",
  },
  // --- Teams: view vs manage ---
  {
    key: "view_teams",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "View teams",
    description: "Allow users to view team list and details",
  },
  {
    key: "view_team_members",
    category: PERMISSION_CATEGORIES.ADMIN_RELATED,
    label: "View team members",
    description: "Allow users to view team members (employees can view their team)",
  },
  // --- Community / Posts (suggestions) - unique keys ---
  {
    key: "create_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Create post",
    description: "Allow users to create a community post",
  },
  {
    key: "view_posts",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View posts",
    description: "Allow users to view community posts",
  },
  {
    key: "view_post_categories",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View post categories",
    description: "Allow users to view post categories",
  },
  {
    key: "edit_own_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Edit own post",
    description: "Allow users to edit their own post",
  },
  {
    key: "edit_any_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Edit any post",
    description: "Allow users to edit any post (admin)",
  },
  {
    key: "delete_own_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Delete own post",
    description: "Allow users to delete their own post",
  },
  {
    key: "delete_any_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Delete any post",
    description: "Allow users to delete any post (admin)",
  },
  {
    key: "respond_to_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Respond to post",
    description: "Allow users to respond to posts (admin)",
  },
  {
    key: "view_all_posts",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View all posts",
    description: "Allow users to view all posts including not responded (admin)",
  },
  {
    key: "view_not_responded_posts_count",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View not responded posts count",
    description: "Allow users to view count of posts not yet responded (admin)",
  },
  {
    key: "like_post",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Like post",
    description: "Allow users to like a post",
  },
  {
    key: "add_post_comment",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Add post comment",
    description: "Allow users to add a comment to a post",
  },
  {
    key: "delete_own_post_comment",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Delete own post comment",
    description: "Allow users to delete their own comment",
  },
  {
    key: "delete_any_post_comment",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Delete any post comment",
    description: "Allow users to delete any comment (admin)",
  },
  {
    key: "edit_own_post_comment",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Edit own post comment",
    description: "Allow users to edit their own comment",
  },
  {
    key: "edit_any_post_comment",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "Edit any post comment",
    description: "Allow users to edit any comment (admin)",
  },
  {
    key: "view_post_likes",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View post likes",
    description: "Allow users to view likes on a post",
  },
  {
    key: "view_post_comments",
    category: PERMISSION_CATEGORIES.COMMUNITY_POSTS,
    label: "View post comments",
    description: "Allow users to view comments on a post",
  },
];

/** Valid permission keys set for validation */
export const ALL_PERMISSION_KEYS = PERMISSION_DEFINITIONS.map((p) => p.key);

/** Default permissions per role (used when company has no role_permissions set) */
export const DEFAULT_ROLE_PERMISSIONS = {
  super_admin: ALL_PERMISSION_KEYS,
  admin: [
    "view_attendance_status",
    "check_in",
    "can_check_out",
    "check_out",
    "view_all_attendance",
    "can_edit_own_attendance",
    "can_edit_all_attendance",
    "can_edit_team_attendance",
    "can_view_all_company_leaves",
    "view_all_leaves_status",
    "save_all_attendance",
    "request_work_from_home",
    "signature_attendance_manage",
    "qr_code_attendance_manage",
    "can_make_new_requests",
    "can_view_own_requests",
    "can_view_all_requests",
    "view_other_requests",
    "can_approve_leave_requests",
    "approve_wfh",
    "cancel_leave_update_leave_request",
    "apply_for_wfh",
    "configure_leave_request_type",
    "manage_leave_rules",
    "view_leave_balance",
    "apply_for_leave",
    "view_leave_requests",
    "view_wfh_requests",
    "request_working_hours",
    "view_working_hours_requests",
    "approve_working_hours_requests",
    "view_reports",
    "view_all_reports",
    "view_attendance_reports",
    "view_time_log_reports",
    "view_audit_trail",
    "manage_reports",
    "view_reports_analytics",
    "manage_all_reports",
    "config_report_settings",
    "export_payroll_data",
    "export_attendance_reports",
    "export_all_reports",
    "export_time_log_reports",
    "manage_user_permissions",
    "manage_agents",
    "manage_office_config",
    "configure_staff_schedules",
    "manage_teams",
    "manage_organization_settings",
    "manage_roles",
    "dynamic_settings",
    "view_recent_requests",
    "view_request_dashboard",
    "can_book_meeting_room",
    "view_meeting_room_bookings",
    "report_bug",
    "view_bugs",
    "manage_bugs",
    "create_ticket",
    "view_tickets",
    "view_ticket_status_count",
    "assign_ticket",
    "update_ticket_status",
    "edit_ticket",
    "delete_ticket",
    "view_departments",
    "manage_departments",
    "view_notifications",
    "send_test_notification",
    "view_teams",
    "view_team_members",
    "create_post",
    "view_posts",
    "view_post_categories",
    "edit_own_post",
    "edit_any_post",
    "delete_own_post",
    "delete_any_post",
    "respond_to_post",
    "view_all_posts",
    "view_not_responded_posts_count",
    "like_post",
    "add_post_comment",
    "delete_own_post_comment",
    "delete_any_post_comment",
    "edit_own_post_comment",
    "edit_any_post_comment",
    "view_post_likes",
    "view_post_comments",
  ],
  teamLead: [
    "view_attendance_status",
    "check_in",
    "can_check_out",
    "check_out",
    "can_edit_own_attendance",
    "view_all_attendance",
    "can_edit_team_attendance",
    "can_view_all_company_leaves",
    "view_all_leaves_status",
    "can_make_new_requests",
    "can_view_own_requests",
    "can_view_all_requests",
    "view_other_requests",
    "can_approve_leave_requests",
    "approve_wfh",
    "cancel_leave_update_leave_request",
    "apply_for_leave",
    "view_leave_balance",
    "view_leave_requests",
    "view_wfh_requests",
    "request_working_hours",
    "view_working_hours_requests",
    "approve_working_hours_requests",
    "view_reports",
    "view_all_reports",
    "view_attendance_reports",
    "view_time_log_reports",
    "view_audit_trail",
    "export_attendance_reports",
    "export_time_log_reports",
    "view_recent_requests",
    "view_request_dashboard",
    "can_book_meeting_room",
    "view_meeting_room_bookings",
    "report_bug",
    "view_bugs",
    "view_departments",
    "manage_own_department",
    "view_notifications",
    "view_teams",
    "view_team_members",
    "create_post",
    "view_posts",
    "view_post_categories",
    "edit_own_post",
    "delete_own_post",
    "like_post",
    "add_post_comment",
    "delete_own_post_comment",
    "edit_own_post_comment",
    "view_post_likes",
    "view_post_comments",
    "create_ticket",
    "view_tickets",
    "view_ticket_status_count",
  ],
  employee: [
    "view_attendance_status",
    "check_in",
    "can_check_out",
    "check_out",
    "can_edit_own_attendance",
    "request_work_from_home",
    "can_view_all_company_leaves",
    "view_all_leaves_status",
    "can_make_new_requests",
    "can_view_own_requests",
    "cancel_leave_update_leave_request",
    "view_leave_balance",
    "apply_for_leave",
    "view_leave_requests",
    "view_wfh_requests",
    "request_working_hours",
    "view_working_hours_requests",
    "view_reports",
    "view_attendance_reports",
    "view_time_log_reports",
    "view_notifications",
    "can_book_meeting_room",
    "view_meeting_room_bookings",
    "report_bug",
    "view_departments",
    "view_teams",
    "view_team_members",
    "create_post",
    "view_posts",
    "view_post_categories",
    "edit_own_post",
    "delete_own_post",
    "like_post",
    "add_post_comment",
    "delete_own_post_comment",
    "edit_own_post_comment",
    "view_post_likes",
    "view_post_comments",
    "create_ticket",
    "view_tickets",
    "view_ticket_status_count",
  ],
};
